### ISSUE TITLE
Website error

### ISSUE THREAD

**Issue by hey-com** [andersnoren/tove#1]
Warning: array_key_exists() expects parameter 2 to be array, null given in /storage/content/15/155915/andersnoren.se/public_html/themes/tove/wp-includes/block-supports/custom-classname.php on line 48

https://andersnoren.se/themes/tove/style-guide/

**Comment by andersnoren** [comment]
@hey-com I don't get that error on the page you linked to. Could be that the WordPress 6.1 update was running while you visited the page and it caused a temporary hickup.
